GET     http://localhost:4000/projects/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJjcmFpZ0B0ZXN0LmNvbSIsIm5hbWUiOiJDcmFpZyBGbGF5ZXIiLCJyb2xlcyI6WyJhZG1pbiJdLCJpYXQiOjE2MzMwMzY0MTksImV4cCI6MTYzMzA0MDAxOX0.5gclm7LGnBuCkS8C39E0rWmZZqb0nVcTRvOtndvrQ-0

